package share.protocol;

public enum RequestType {
    LOGIN, LOGOUT, REGISTER, GET_LIST_USER, CREATE_CONVERSATION_PRIVATE, CREATE_CONVERSATION_GROUP, GET_LIST_CONVERSATION,GET_LIST_MESSAGE, SEND_MESSAGE;
}
