package share.protocol;

public enum ResponseType {
    LOGIN, LOGOUT, REGISTER, GET_LIST_USER, CREATE_CONVERSATION, GET_LIST_CONVERSATION,GET_LIST_MESSAGE,
    BROADCAST_LIST_USER, NOTIFY_LIST_CONVERSATION;
}
