package share.protocol;

public enum ResponseType {
    LOGIN, LOGOUT, REGISTER, GET_LIST_USER, CREATE_CONVERSATION_PRIVATE,CREATE_CONVERSATION_GROUP, GET_LIST_CONVERSATION,GET_LIST_MESSAGE,SEND_MESSAGE,
    BROADCAST_LIST_USER, NOTIFY_LIST_CONVERSATION, NOTIFY_LIST_MESSAGE;
}
